### ISSUE TITLE
Algunas descripciones de las charlas no se muestran...

### ISSUE THREAD

**Issue by bertothunder** [python-spain/PyConES-2017#11]
Para algunas de las charlas, las descripciones no aparecen si se hace click en el enlace; sin embargo, se muestran perfectamente en el desplegable, haciendo click en la flecha hacia abajo. Para otras charlas, todo funciona como se espera.

Sucede, ahora mismo, en:

Patrones de diseño: Python boloñesa
Parallel and no parallel stuff
Codelab: ¿Podemos predecir quién muere en Juego de Tronos con TensorFlow?
High-impact refactors while keeping the lights on 
City attractiveness seen through Twitter
Mi coche ya es mayor de edad, creo que puede conducir él solito
NASAL-Geom: Salvando vidas con Python 
Sistemas Expertos en Python con PyKnow
¡Atrapa ese asteroide con poliastro!
Metaclases: exactamente qué y (sobre todo) por qué 
Tu web está lista, ¿lo sabe Google?
Cómo diseñar un programa CLI fácil de lanzar, con un Click

**Comment by marcosgabarda** [comment]
Arreglado en 8f17e4ad85aa0049cbe78ad7a6b622549ef86689
