### ISSUE TITLE
https://es.pycon.org/ redirige a https://2019.es.pycon.org/

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2017#56]
Debería redirigir a https://2020.es.pycon.org/

**Comment by apslsistemas** [comment]
Veo la IP apuntando a : 176.9.11.11
Help @jcea! ¿Puede que este redirect lo controles tu?
¿O quizá @yamila-moreno en algún server de scaleway?

**Comment by eduherraiz** [comment]
Veo la IP apuntando a : 176.9.11.11
Help @jcea! ¿Puede que este redirect lo controles tu?
¿O quizá @yamila-moreno en algún server de scaleway?

**Comment by kikocorreoso** [comment]
Done!!

Thanks @jcea !!!!

Se puede cerrar.

**Comment by apslsistemas** [comment]
Funciona! cierro
